# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CCA.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!
from PyQt4 import QtCore, QtGui
from PyQt4.QtGui import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(960, 540)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.addRecord = QtGui.QFrame(self.centralwidget)
        self.addRecord.setGeometry(QtCore.QRect(-1, -1, 961, 561))
        # self.addRecord.setAutoFillBackground(True)
        # self.addRecord.setFrameShape(QtGui.QFrame.StyledPanel)
        # self.addRecord.setFrameShadow(QtGui.QFrame.Raised)
        MainWindow.setAutoFillBackground(True)
        window_pale = QtGui.QPalette()
        painter = QPainter()
        pixmap = QPixmap("../resource/background.png")
        painter.drawPixmap(self.addRecord.rect(), pixmap)

        window_pale.setBrush(MainWindow.backgroundRole(),
                             QBrush(QPixmap("../resource/background.png")))
        # self.centralwidget.setPalette(window_pale)
        # self.addRecord.setWindowIcon(QIcon("../resource/background.png"))
        # self.addRecord.setPalette(window_pale)
        self.addRecord.setObjectName(_fromUtf8("addRecord"))
        self.addRecord.setStyleSheet("QFrame#addRecord{border-image:url(../resource/background.png);}")

        # self.setStyleSheet("QFrame#addRecord{border-image:url(../resource/background.png);}")
        self.gridLayoutWidget = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 10, 314, 50))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.title = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setTextFormat(QtCore.Qt.PlainText)
        self.title.setScaledContents(False)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName(_fromUtf8("title"))
        # self.lab = QLabel("设置背景图片",MainWindow)
        # self.lab.setGeometry(0,0,960,540)
        # self.addRecord.setAutoFillBackground(True)
        window_pale = QtGui.QPalette()
        window_pale.setBrush(QPalette.Background, QBrush(QPixmap("../resource/background.png")))
        self.addRecord.setPalette(window_pale)
        s = QtGui.QPixmap("../resource/background.png")
        # self.addRecord.setStyleSheet('background-image: url("../resource/background.png")')
        # MainWindow.setAutoFillBackground(True)
        # MainWindow.setPalette(window_pale)
        self.gridLayout.addWidget(self.title, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(160, 60, 101, 41))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.share_code_title = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.share_code_title.setFont(font)
        self.share_code_title.setTextFormat(QtCore.Qt.PlainText)
        self.share_code_title.setAlignment(QtCore.Qt.AlignCenter)
        self.share_code_title.setObjectName(_fromUtf8("share_code_title"))
        self.gridLayout_2.addWidget(self.share_code_title, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(160, 110, 101, 41))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.buy_date_title = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buy_date_title.setFont(font)
        self.buy_date_title.setTextFormat(QtCore.Qt.PlainText)
        self.buy_date_title.setAlignment(QtCore.Qt.AlignCenter)
        self.buy_date_title.setObjectName(_fromUtf8("buy_date_title"))
        self.gridLayout_3.addWidget(self.buy_date_title, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(160, 160, 101, 41))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.buy_price_title = QtGui.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buy_price_title.setFont(font)
        self.buy_price_title.setTextFormat(QtCore.Qt.PlainText)
        self.buy_price_title.setAlignment(QtCore.Qt.AlignCenter)
        self.buy_price_title.setObjectName(_fromUtf8("buy_price_title"))
        self.gridLayout_4.addWidget(self.buy_price_title, 0, 0, 1, 1)
        self.gridLayoutWidget_5 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(160, 210, 101, 41))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.buy_num_title = QtGui.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buy_num_title.setFont(font)
        self.buy_num_title.setTextFormat(QtCore.Qt.PlainText)
        self.buy_num_title.setAlignment(QtCore.Qt.AlignCenter)
        self.buy_num_title.setObjectName(_fromUtf8("buy_num_title"))
        self.gridLayout_5.addWidget(self.buy_num_title, 0, 0, 1, 1)
        self.gridLayoutWidget_6 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(160, 260, 101, 41))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.have_avg_price = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.have_avg_price.setFont(font)
        self.have_avg_price.setTextFormat(QtCore.Qt.PlainText)
        self.have_avg_price.setAlignment(QtCore.Qt.AlignCenter)
        self.have_avg_price.setObjectName(_fromUtf8("have_avg_price"))
        self.gridLayout_6.addWidget(self.have_avg_price, 0, 0, 1, 1)
        self.gridLayoutWidget_7 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(160, 310, 101, 41))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.have_num_title = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.have_num_title.setFont(font)
        self.have_num_title.setTextFormat(QtCore.Qt.PlainText)
        self.have_num_title.setAlignment(QtCore.Qt.AlignCenter)
        self.have_num_title.setObjectName(_fromUtf8("have_num_title"))
        self.gridLayout_7.addWidget(self.have_num_title, 0, 0, 1, 1)
        self.gridLayoutWidget_8 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(450, 260, 101, 41))
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.have_avg_price_2 = QtGui.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.have_avg_price_2.setFont(font)
        self.have_avg_price_2.setTextFormat(QtCore.Qt.PlainText)
        self.have_avg_price_2.setAlignment(QtCore.Qt.AlignCenter)
        self.have_avg_price_2.setObjectName(_fromUtf8("have_avg_price_2"))
        self.gridLayout_8.addWidget(self.have_avg_price_2, 0, 0, 1, 1)
        self.gridLayoutWidget_9 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(450, 310, 101, 41))
        self.gridLayoutWidget_9.setObjectName(_fromUtf8("gridLayoutWidget_9"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.can_sale_num_title = QtGui.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.can_sale_num_title.setFont(font)
        self.can_sale_num_title.setTextFormat(QtCore.Qt.PlainText)
        self.can_sale_num_title.setAlignment(QtCore.Qt.AlignCenter)
        self.can_sale_num_title.setObjectName(_fromUtf8("can_sale_num_title"))
        self.gridLayout_9.addWidget(self.can_sale_num_title, 0, 0, 1, 1)
        self.gridLayoutWidget_10 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(450, 110, 101, 41))
        self.gridLayoutWidget_10.setObjectName(_fromUtf8("gridLayoutWidget_10"))
        self.gridLayout_10 = QtGui.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.buy_date_title_2 = QtGui.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buy_date_title_2.setFont(font)
        self.buy_date_title_2.setTextFormat(QtCore.Qt.PlainText)
        self.buy_date_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.buy_date_title_2.setObjectName(_fromUtf8("buy_date_title_2"))
        self.gridLayout_10.addWidget(self.buy_date_title_2, 0, 0, 1, 1)
        self.gridLayoutWidget_11 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(450, 160, 101, 41))
        self.gridLayoutWidget_11.setObjectName(_fromUtf8("gridLayoutWidget_11"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.buy_price_title_2 = QtGui.QLabel(self.gridLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buy_price_title_2.setFont(font)
        self.buy_price_title_2.setTextFormat(QtCore.Qt.PlainText)
        self.buy_price_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.buy_price_title_2.setObjectName(_fromUtf8("buy_price_title_2"))
        self.gridLayout_11.addWidget(self.buy_price_title_2, 0, 0, 1, 1)
        self.gridLayoutWidget_12 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(450, 60, 101, 41))
        self.gridLayoutWidget_12.setObjectName(_fromUtf8("gridLayoutWidget_12"))
        self.gridLayout_12 = QtGui.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.share_code_title_2 = QtGui.QLabel(self.gridLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.share_code_title_2.setFont(font)
        self.share_code_title_2.setTextFormat(QtCore.Qt.PlainText)
        self.share_code_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.share_code_title_2.setObjectName(_fromUtf8("share_code_title_2"))
        self.gridLayout_12.addWidget(self.share_code_title_2, 0, 0, 1, 1)
        self.gridLayoutWidget_13 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(450, 210, 101, 41))
        self.gridLayoutWidget_13.setObjectName(_fromUtf8("gridLayoutWidget_13"))
        self.gridLayout_13 = QtGui.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.buy_num_title_2 = QtGui.QLabel(self.gridLayoutWidget_13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei Mono"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buy_num_title_2.setFont(font)
        self.buy_num_title_2.setTextFormat(QtCore.Qt.PlainText)
        self.buy_num_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.buy_num_title_2.setObjectName(_fromUtf8("buy_num_title_2"))
        self.gridLayout_13.addWidget(self.buy_num_title_2, 0, 0, 1, 1)
        self.gridLayoutWidget_14 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_14.setGeometry(QtCore.QRect(280, 60, 141, 50))
        self.gridLayoutWidget_14.setObjectName(_fromUtf8("gridLayoutWidget_14"))
        self.gridLayout_14 = QtGui.QGridLayout(self.gridLayoutWidget_14)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.share_code_input = QtGui.QLineEdit(self.gridLayoutWidget_14)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.share_code_input.setFont(font)
        self.share_code_input.setObjectName(_fromUtf8("share_code_input"))
        self.gridLayout_14.addWidget(self.share_code_input, 0, 0, 1, 1)
        self.gridLayoutWidget_15 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_15.setGeometry(QtCore.QRect(280, 110, 141, 41))
        self.gridLayoutWidget_15.setObjectName(_fromUtf8("gridLayoutWidget_15"))
        self.gridLayout_15 = QtGui.QGridLayout(self.gridLayoutWidget_15)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.buy_date_input = QtGui.QDateEdit(self.gridLayoutWidget_15)
        self.buy_date_input.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.buy_date_input.sizePolicy().hasHeightForWidth())
        self.buy_date_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei UI Light"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.buy_date_input.setFont(font)
        self.buy_date_input.setWrapping(False)
        self.buy_date_input.setFrame(False)
        self.buy_date_input.setDate(QtCore.QDate(2018, 11, 11))
        self.buy_date_input.setObjectName(_fromUtf8("buy_date_input"))
        self.gridLayout_15.addWidget(self.buy_date_input, 0, 0, 1, 1)
        self.gridLayoutWidget_16 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_16.setGeometry(QtCore.QRect(280, 210, 141, 41))
        self.gridLayoutWidget_16.setObjectName(_fromUtf8("gridLayoutWidget_16"))
        self.gridLayout_16 = QtGui.QGridLayout(self.gridLayoutWidget_16)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.buy_num_input = QtGui.QSpinBox(self.gridLayoutWidget_16)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei UI Light"))
        font.setPointSize(14)
        self.buy_num_input.setFont(font)
        self.buy_num_input.setFrame(False)
        self.buy_num_input.setMinimum(1)
        self.buy_num_input.setMaximum(99999999)
        self.buy_num_input.setObjectName(_fromUtf8("buy_num_input"))
        self.gridLayout_16.addWidget(self.buy_num_input, 0, 0, 1, 1)
        self.gridLayoutWidget_17 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_17.setGeometry(QtCore.QRect(280, 160, 141, 41))
        self.gridLayoutWidget_17.setObjectName(_fromUtf8("gridLayoutWidget_17"))
        self.gridLayout_17 = QtGui.QGridLayout(self.gridLayoutWidget_17)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.buy_price_input = QtGui.QDoubleSpinBox(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI Light"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.buy_price_input.setFont(font)
        self.buy_price_input.setFrame(False)
        self.buy_price_input.setMinimum(1.0)
        self.buy_price_input.setMaximum(999.99)
        self.buy_price_input.setObjectName(_fromUtf8("buy_price_input"))
        self.gridLayout_17.addWidget(self.buy_price_input, 0, 0, 1, 1)
        self.gridLayoutWidget_18 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_18.setGeometry(QtCore.QRect(280, 310, 141, 41))
        self.gridLayoutWidget_18.setObjectName(_fromUtf8("gridLayoutWidget_18"))
        self.gridLayout_18 = QtGui.QGridLayout(self.gridLayoutWidget_18)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.have_num_show = QtGui.QLineEdit(self.gridLayoutWidget_18)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei UI Light"))
        font.setPointSize(14)
        self.have_num_show.setFont(font)
        self.have_num_show.setReadOnly(True)
        self.have_num_show.setFrame(False)
        self.have_num_show.setObjectName(_fromUtf8("have_num_show"))
        self.gridLayout_18.addWidget(self.have_num_show, 0, 0, 1, 1)
        self.gridLayoutWidget_19 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_19.setGeometry(QtCore.QRect(280, 260, 141, 41))
        self.gridLayoutWidget_19.setObjectName(_fromUtf8("gridLayoutWidget_19"))
        self.gridLayout_19 = QtGui.QGridLayout(self.gridLayoutWidget_19)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.buv_avg_price_show = QtGui.QLineEdit(self.gridLayoutWidget_19)
        self.buv_avg_price_show.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei UI Light"))
        font.setPointSize(14)
        self.buv_avg_price_show.setFont(font)
        self.buv_avg_price_show.setReadOnly(True)
        self.buv_avg_price_show.setFrame(False)
        self.buv_avg_price_show.setObjectName(_fromUtf8("buv_avg_price_show"))
        self.gridLayout_19.addWidget(self.buv_avg_price_show, 0, 0, 1, 1)
        self.gridLayoutWidget_20 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_20.setGeometry(QtCore.QRect(570, 110, 141, 41))
        self.gridLayoutWidget_20.setObjectName(_fromUtf8("gridLayoutWidget_20"))
        self.gridLayout_20 = QtGui.QGridLayout(self.gridLayoutWidget_20)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.sale_date_input = QtGui.QDateEdit(self.gridLayoutWidget_20)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei UI Light"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.sale_date_input.setFont(font)
        self.sale_date_input.setWrapping(False)
        self.sale_date_input.setFrame(False)
        self.sale_date_input.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 11, 11), QtCore.QTime(0, 0, 0)))
        self.sale_date_input.setObjectName(_fromUtf8("sale_date_input"))
        self.gridLayout_20.addWidget(self.sale_date_input, 0, 0, 1, 1)
        self.gridLayoutWidget_21 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_21.setGeometry(QtCore.QRect(570, 60, 141, 50))
        self.gridLayoutWidget_21.setObjectName(_fromUtf8("gridLayoutWidget_21"))
        self.gridLayout_21 = QtGui.QGridLayout(self.gridLayoutWidget_21)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.share_name_show = QtGui.QLineEdit(self.gridLayoutWidget_21)
        self.share_name_show.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI Light"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.share_name_show.setFont(font)
        self.share_name_show.setReadOnly(True)
        self.share_name_show.setFrame(False)
        self.share_name_show.setObjectName(_fromUtf8("share_name_show"))
        self.gridLayout_21.addWidget(self.share_name_show, 0, 0, 1, 1)
        self.gridLayoutWidget_22 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_22.setGeometry(QtCore.QRect(570, 160, 141, 41))
        self.gridLayoutWidget_22.setObjectName(_fromUtf8("gridLayoutWidget_22"))
        self.gridLayout_22 = QtGui.QGridLayout(self.gridLayoutWidget_22)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.sale_price_input = QtGui.QDoubleSpinBox(self.gridLayoutWidget_22)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI Light"))
        font.setPointSize(14)
        self.sale_price_input.setFont(font)
        self.sale_price_input.setFrame(False)
        self.sale_price_input.setMinimum(1.0)
        self.sale_price_input.setMaximum(999.99)
        self.sale_price_input.setObjectName(_fromUtf8("sale_price_input"))
        self.gridLayout_22.addWidget(self.sale_price_input, 0, 0, 1, 1)
        self.gridLayoutWidget_23 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_23.setGeometry(QtCore.QRect(570, 310, 141, 41))
        self.gridLayoutWidget_23.setObjectName(_fromUtf8("gridLayoutWidget_23"))
        self.gridLayout_23 = QtGui.QGridLayout(self.gridLayoutWidget_23)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.can_sale_num_show = QtGui.QLineEdit(self.gridLayoutWidget_23)
        self.can_sale_num_show.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei UI Light"))
        font.setPointSize(14)
        self.can_sale_num_show.setFont(font)
        self.can_sale_num_show.setReadOnly(True)
        self.can_sale_num_show.setFrame(False)
        self.can_sale_num_show.setObjectName(_fromUtf8("can_sale_num_show"))
        self.gridLayout_23.addWidget(self.can_sale_num_show, 0, 0, 1, 1)
        self.gridLayoutWidget_24 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_24.setGeometry(QtCore.QRect(570, 260, 141, 41))
        self.gridLayoutWidget_24.setObjectName(_fromUtf8("gridLayoutWidget_24"))
        self.gridLayout_24 = QtGui.QGridLayout(self.gridLayoutWidget_24)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.win_show = QtGui.QLineEdit(self.gridLayoutWidget_24)
        self.win_show.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei UI Light"))
        font.setPointSize(14)
        self.win_show.setFont(font)
        self.win_show.setReadOnly(True)
        self.win_show.setObjectName(_fromUtf8("win_show"))
        self.win_show.setFrame(False)
        self.gridLayout_24.addWidget(self.win_show, 0, 0, 1, 1)
        self.gridLayoutWidget_25 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_25.setGeometry(QtCore.QRect(570, 210, 141, 41))
        self.gridLayoutWidget_25.setObjectName(_fromUtf8("gridLayoutWidget_25"))
        self.gridLayout_25 = QtGui.QGridLayout(self.gridLayoutWidget_25)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.sale_num_input = QtGui.QSpinBox(self.gridLayoutWidget_25)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft JhengHei UI Light"))
        font.setPointSize(14)
        self.sale_num_input.setFont(font)
        self.sale_num_input.setFrame(False)
        self.sale_num_input.setMinimum(1)
        self.sale_num_input.setMaximum(99999999)
        self.sale_num_input.setObjectName(_fromUtf8("sale_num_input"))
        self.gridLayout_25.addWidget(self.sale_num_input, 0, 0, 1, 1)

        self.gridLayoutWidget_26 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_26.setGeometry(QtCore.QRect(160, 390, 121, 50))
        self.gridLayoutWidget_26.setObjectName(_fromUtf8("gridLayoutWidget_26"))
        self.gridLayout_26 = QtGui.QGridLayout(self.gridLayoutWidget_26)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.query_button = QtGui.QPushButton(self.gridLayoutWidget_26)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.query_button.setFont(font)
        self.query_button.setFlat(False)
        # self.query_button.setStyleSheet("#gridLayout_26{backgroud-color:#0000ff)}")
        self.query_button.setObjectName(_fromUtf8("query_button"))
        self.gridLayout_26.addWidget(self.query_button, 0, 0, 1, 1)
        self.gridLayoutWidget_27 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_27.setGeometry(QtCore.QRect(300, 390, 121, 50))
        self.gridLayoutWidget_27.setObjectName(_fromUtf8("gridLayoutWidget_27"))
        self.gridLayout_27 = QtGui.QGridLayout(self.gridLayoutWidget_27)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.compute_button = QtGui.QPushButton(self.gridLayoutWidget_27)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.compute_button.setFont(font)
        self.compute_button.setObjectName(_fromUtf8("compute_button"))
        self.gridLayout_27.addWidget(self.compute_button, 0, 0, 1, 1)
        self.gridLayoutWidget_28 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_28.setGeometry(QtCore.QRect(440, 390, 121, 50))
        self.gridLayoutWidget_28.setObjectName(_fromUtf8("gridLayoutWidget_28"))
        self.gridLayout_28 = QtGui.QGridLayout(self.gridLayoutWidget_28)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.save_button = QtGui.QPushButton(self.gridLayoutWidget_28)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.save_button.setFont(font)
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.gridLayout_28.addWidget(self.save_button, 0, 0, 1, 1)
        self.gridLayoutWidget_29 = QtGui.QWidget(self.addRecord)
        self.gridLayoutWidget_29.setGeometry(QtCore.QRect(570, 390, 160, 73))
        self.gridLayoutWidget_29.setObjectName(_fromUtf8("gridLayoutWidget_29"))
        self.gridLayout_29 = QtGui.QGridLayout(self.gridLayoutWidget_29)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.textEdit = QtGui.QTextEdit(self.gridLayoutWidget_29)
        self.textEdit.setEnabled(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setFrameShape(False)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_29.addWidget(self.textEdit, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.edit = QtGui.QMenu(self.menubar)
        self.edit.setObjectName(_fromUtf8("edit"))
        self.tool = QtGui.QMenu(self.menubar)
        self.tool.setObjectName(_fromUtf8("tool"))
        self.program = QtGui.QMenu(self.menubar)
        self.program.setObjectName(_fromUtf8("program"))
        self.help = QtGui.QMenu(self.menubar)
        self.help.setObjectName(_fromUtf8("help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.add = QtGui.QAction(MainWindow)
        self.add.setObjectName(_fromUtf8("add"))
        self.query = QtGui.QAction(MainWindow)
        self.query.setObjectName(_fromUtf8("query"))
        self.deleteRecord = QtGui.QAction(MainWindow)
        self.deleteRecord.setObjectName(_fromUtf8("deleteRecord"))
        self.addShare = QtGui.QAction(MainWindow)
        self.addShare.setObjectName(_fromUtf8("addShare"))
        self.importShare = QtGui.QAction(MainWindow)
        self.importShare.setObjectName(_fromUtf8("importShare"))
        self.login = QtGui.QAction(MainWindow)
        self.login.setObjectName(_fromUtf8("login"))
        self.logout = QtGui.QAction(MainWindow)
        self.logout.setObjectName(_fromUtf8("logout"))
        self.exit = QtGui.QAction(MainWindow)
        self.exit.setObjectName(_fromUtf8("exit"))
        self.about = QtGui.QAction(MainWindow)
        self.about.setObjectName(_fromUtf8("about"))
        self.edit.addAction(self.add)
        self.edit.addAction(self.query)
        self.edit.addAction(self.deleteRecord)
        self.tool.addAction(self.addShare)
        self.tool.addAction(self.importShare)
        self.tool.addSeparator()
        self.tool.addAction(self.login)
        self.tool.addAction(self.logout)
        self.program.addAction(self.exit)
        self.help.addAction(self.about)
        self.menubar.addAction(self.edit.menuAction())
        self.menubar.addAction(self.tool.menuAction())
        self.menubar.addAction(self.program.menuAction())
        self.menubar.addAction(self.help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "驰骋A股", None))
        self.title.setText(_translate("MainWindow", "新增交易记录", None))
        self.share_code_title.setText(_translate("MainWindow", "股票代码", None))
        self.buy_date_title.setText(_translate("MainWindow", "买入日期", None))
        self.buy_price_title.setText(_translate("MainWindow", "买入价格", None))
        self.buy_num_title.setText(_translate("MainWindow", "买入数量", None))
        self.have_avg_price.setText(_translate("MainWindow", "持仓均价", None))
        self.have_num_title.setText(_translate("MainWindow", "持仓数量", None))
        self.have_avg_price_2.setText(_translate("MainWindow", "当前盈利", None))
        self.can_sale_num_title.setText(_translate("MainWindow", "可卖数量", None))
        self.buy_date_title_2.setText(_translate("MainWindow", "卖出日期", None))
        self.buy_price_title_2.setText(_translate("MainWindow", "卖出价格", None))
        self.share_code_title_2.setText(_translate("MainWindow", "股票名称", None))
        self.buy_num_title_2.setText(_translate("MainWindow", "卖出数量", None))
        self.query_button.setText(_translate("MainWindow", "查询", None))
        self.compute_button.setText(_translate("MainWindow", "计算", None))
        self.save_button.setText(_translate("MainWindow", "保存", None))
        self.textEdit.setHtml(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">数量单位:手(1手=100股)</p>\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">货币单位:元</p></body></html>",
                                         None))
        self.edit.setTitle(_translate("MainWindow", "编辑", None))
        self.tool.setTitle(_translate("MainWindow", "工具", None))
        self.program.setTitle(_translate("MainWindow", "程序", None))
        self.help.setTitle(_translate("MainWindow", "帮助", None))

        self.add.setText(_translate("MainWindow", "新增交易记录", None))
        self.query.setText(_translate("MainWindow", "查询交易记录", None))
        self.deleteRecord.setText(_translate("MainWindow", "删除交易记录", None))
        self.addShare.setText(_translate("MainWindow", "新增股票信息", None))
        self.importShare.setText(_translate("MainWindow", "导入股票信息", None))
        self.login.setText(_translate("MainWindow", "登录", None))
        self.logout.setText(_translate("MainWindow", "注销", None))
        self.exit.setText(_translate("MainWindow", "退出", None))
        self.about.setText(_translate("MainWindow", "关于", None))


if __name__ == "__main__":
    import sys

    app = QtGui.QApplication(sys.argv)
    widget = QMainWindow()
    s = Ui_MainWindow()

    s.setupUi(widget)

    widget.show()

    sys.exit(app.exec_())
